version: '3'
services:
    webserver:
        build:
            ./docker/webserver
        ports:
            - 80:80
        volumes:
            - ./DocumentRoot:/var/www/html
        links:
            - 'mariadb'
    mariadb:
        image: mariadb:10.3
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: fh_2018_scm4
            MYSQL_PASSWORD: fh_2018_scm4
            MYSQL_DATABASE: fh_2018_scm4_S1610307036
