version: '3'
services:
    webserver:
        build:
            ./docker/webserver
        ports:
            - 80:80
        volumes:
            - ./DocumentRoot:/var/www/html
            - ./docker/webserver/apache2.conf:/etc/apache2/apache2.conf
            - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - 'mariadb'
    mariadb:
        build:
            ./docker/mariadb
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: fh_2018_scm4
            MYSQL_PASSWORD: fh_2018_scm4
            MYSQL_DATABASE: fh_2018_scm4_S1610307036
