version: '3'
services:
    webserver:
        build:
            ./docker/webserver
        ports:
            - 80:80
        volumes:
            - ./DocumentRoot:/var/www/html
            - ./docker/webserver/apache2.conf:/etc/apache2/apache2.conf
            - ./docker/webserver/php.ini:/usr/local/etc/php/conf.d/php.ini
        links:
            - 'mariadb'
    mariadb:
        build:
            ./docker/mariadb
        volumes:
      #     - ./db:/var/lib/mysql
            - ./database/db_strcuture_and_dummy_data.sql:/docker-entrypoint-initdb.d/db_strcuture_and_dummy_data.sql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: fh_2018_scm4
            MYSQL_PASSWORD: fh_2018_scm4
            MYSQL_DATABASE: fh_2018_scm4_s1610307036
